---

- name: create /etc/prometheus
  file:
    path: /etc/prometheus
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create the prometheus user
  group:
    name: prometheus
    state: present

- name: create the prometheus user
  user:
    name: prometheus
    group: prometheus
    shell: /bin/false
    create_home: false
    state: present

- name: create /var/lib/prometheus
  file:
    path: /var/lib/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755

- name: fetch latest nginx-prometheus-exporter version
  shell: curl -s -o /dev/null -I -w "%{redirect_url}\n" https://github.com/nginxinc/nginx-prometheus-exporter/releases/latest | grep -oP "[0-9]+(\.[0-9]+)+$"
  args:
    executable: /bin/bash
  register: nginx_exporter_version

- name: download nginx-prometheus-exporter
  get_url:
    url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v{{ nginx_exporter_version.stdout }}/nginx-prometheus-exporter-{{ nginx_exporter_version.stdout }}-linux-amd64.tar.gz
    owner: root
    group: root
    dest: /root/nginx-prometheus-exporter-{{ nginx_exporter_version.stdout }}-linux-amd64.tar.gz
    mode: 0755

- name: Unarchive nginxprometheus-exporter
  unarchive:
    src: /root/nginx-prometheus-exporter-{{ nginx_exporter_version.stdout }}-linux-amd64.tar.gz
    dest: /root
    remote_src: yes

- name: copy nginx-prometheus-exporter to /usr/local/bin/nginx-prometheus-exporter
  copy:
    src: /root/nginx-prometheus-exporter
    dest: /usr/local/bin/nginx-prometheus-exporter
    owner: prometheus
    group: prometheus
    mode: 0755
    remote_src: yes

- name: add nginx-prometheus-exporter systemd unit file
  template:
    src: nginx-prometheus-exporter.service
    dest: /etc/systemd/system/nginx-prometheus-exporter.service
    mode: 0644

- name: just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: enable nginx-prometheus-exporter
  systemd:
    name: nginx-prometheus-exporter
    enabled: yes

- name: start nginx-prometheus-exporter
  systemd:
    name: nginx-prometheus-exporter
    state: started

...
